### ISSUE TITLE
Error in Post Example on CodeSandBox

### ISSUE THREAD

**Issue by its4zahoor** [sergey-s/use-axios-react#2]
When I open the [POST Example in CodeSandBox](https://codesandbox.io/s/post-example-kd0eb) it gives the following error.
**TypeError
_usePostCallback2[3] is undefined**

I am unable to resolve it as apparently usePostCallBack is defined(imported from lib).

**Comment by sergey-s** [comment]
@its4zahoor Fixed the example, thank you for reporting. Also you've referred to a link from one of the previous lib versions, check the most recent one - https://codesandbox.io/s/post-example-8x59c?fontsize=14 (referenced in README)
