### ISSUE TITLE
using multiple axios instances

### ISSUE THREAD

**Issue by sahanatroam** [sergey-s/use-axios-react#5]
Hi @sergey-s ,

What if you need to use multiple `axios` instances ? with different base_urls and headers ?
How would you handle that in this case

Why don't we change the library to accept a axios instance as a param ? not as a global setting ?

**Comment by sahanatroam** [comment]
@sergey-s ping

**Comment by sergey-s** [comment]
> What if you need to use multiple axios instances ? with different base_urls and headers ?
How would you handle that in this case

I'd either not used a base instance at all and would just use the full config each time, or I'd create multiple modules wrapping lib's functions to add the needed settings (prepend url, add headers etc) if had to reuse it a lot

> Why don't we change the library to accept a axios instance as a param ? not as a global setting ?

A single instance is what's been sufficient even when app talked to multiple APIs. You can fork and add something you need, it's open source ;)
