### ISSUE TITLE
The Basic POST example doesn't work

### ISSUE THREAD

**Issue by quangdung** [sergey-s/use-axios-react#6]
Hello, the "[Basic POST example doesn't work](https://codesandbox.io/s/post-example-8x59c?fontsize=14)" displays this error:

![image](https://user-images.githubusercontent.com/6871103/72810244-71608f00-3c5d-11ea-8058-6256e588ad67.png)

**Comment by rjstires** [comment]
```js
const [create, sending, { error, data }] = usePostCallback(userToRequest);
```

What you've posted and what is in the documentation currently are not the same. Maybe it was updated?

**Comment by sergey-s** [comment]
This sandbox is for the previous lib version, the API has been updated, see the comment above
